version = 1

[envs.huggingface_hub]
channels = ["conda-forge"]
dependencies = { huggingface_hub = "*" }
exposed = { hf = "hf"}

[envs.kaggle]
channels = ["conda-forge"]
dependencies = { kaggle = "*" }
exposed = { kaggle = "kaggle" }
