[tools]
bat = "latest"
claude = "latest"
antigravity-cli = "latest"
eza = "latest"
fd = "latest"
go = "1.22"
node = "24"
ripgrep = "latest"
tree-sitter = "latest"
zoxide = "latest"
lazydocker = "latest"
"github:jesseduffield/lazygit" = "latest"
"github:junegunn/fzf" = "latest"
"github:neovim/neovim" = "latest"
"github:zellij-org/zellij" = "latest"
"github:starship/starship" = "latest"
